
import { Dimensions, Platform, StatusBar, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const topPadding = Platform.OS === 'ios' ? 44 : (StatusBar.currentHeight || 20);
const titleFont = Platform.select({ ios: 'Avenir Next', android: 'sans-serif-condensed', default: 'System' });

export function createStyles(c) {
  return StyleSheet.create({
    root:{flex:1,backgroundColor:c.bg,paddingTop:topPadding},
    header:{paddingHorizontal:20,paddingTop:8,paddingBottom:16,borderBottomWidth:1,borderBottomColor:c.line,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},
    brandRow:{flexDirection:'row',alignItems:'center',flex:1},
    logo:{width:52,height:52,borderRadius:18,backgroundColor:c.gold,alignItems:'center',justifyContent:'center',marginRight:12},
    logoText:{color:'#111',fontWeight:'900',fontSize:20},
    brandTitle:{color:c.ink,fontFamily:titleFont,fontSize:28,fontWeight:'900',letterSpacing:-1},
    brandSub:{color:c.muted,fontSize:13,marginTop:2},
    pill:{borderWidth:1,borderColor:c.goldLine,borderRadius:20,paddingHorizontal:12,paddingVertical:7,marginLeft:8},
    pillActive:{backgroundColor:c.gold},
    pillText:{color:c.gold2,fontWeight:'900',fontSize:12},
    pillTextActive:{color:'#111'},
    scroll:{paddingHorizontal:20,paddingTop:22,paddingBottom:120},
    hero:{borderRadius:30,borderWidth:1,borderColor:c.goldLine,backgroundColor:c.card,padding:20,marginBottom:22,overflow:'hidden'},
    heroTitle:{color:c.ink,fontFamily:titleFont,fontSize:34,lineHeight:38,fontWeight:'900',marginTop:14,letterSpacing:-1},
    heroText:{color:c.muted,fontSize:16,lineHeight:23,marginTop:8},
    chipRow:{flexDirection:'row',justifyContent:'space-between',marginTop:14},
    chip:{backgroundColor:c.goldSoft,borderWidth:1,borderColor:c.goldLine,borderRadius:999,paddingHorizontal:12,paddingVertical:7},
    chipText:{color:c.gold2,fontWeight:'900',fontSize:12},
    actionRow:{flexDirection:'row',marginTop:16},
    primary:{flex:1,backgroundColor:c.gold,borderRadius:18,paddingVertical:14,alignItems:'center',marginRight:8},
    secondary:{flex:1,borderWidth:1,borderColor:c.line2,borderRadius:18,paddingVertical:14,alignItems:'center',marginRight:8},
    primaryText:{color:'#111',fontWeight:'900'},
    secondaryText:{color:c.ink,fontWeight:'900'},
    section:{marginTop:20,marginBottom:10},
    sectionTitle:{color:c.ink,fontFamily:titleFont,fontWeight:'900',fontSize:24},
    sectionSub:{color:c.soft,fontSize:14,lineHeight:19,marginTop:3},
    pageTitle:{color:c.ink,fontFamily:titleFont,fontSize:38,fontWeight:'900',letterSpacing:-1},
    pageSub:{color:c.muted,fontSize:16,lineHeight:23,marginTop:5,marginBottom:16},
    search:{backgroundColor:c.card3,borderWidth:1,borderColor:c.line,borderRadius:20,paddingHorizontal:16,paddingVertical:14,color:c.ink,fontSize:16,marginBottom:14},
    card:{backgroundColor:c.card,borderWidth:1,borderColor:c.line,borderRadius:26,padding:16,marginBottom:12},
    cardActive:{borderColor:c.goldLine,backgroundColor:c.goldSoft},
    row:{flexDirection:'row'},
    grow:{flex:1},
    tag:{color:c.gold2,fontSize:11,fontWeight:'900',textTransform:'uppercase',marginBottom:5},
    title:{color:c.ink,fontFamily:titleFont,fontSize:21,fontWeight:'900',lineHeight:24},
    text:{color:c.muted,fontSize:14,lineHeight:20,marginTop:6},
    small:{color:c.soft,fontSize:12,lineHeight:18},
    gold:{color:c.gold2,fontWeight:'900'},
    iconBox:{width:54,height:54,borderRadius:18,backgroundColor:c.goldSoft,alignItems:'center',justifyContent:'center',marginRight:14},
    icon:{fontSize:25},
    grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'},
    half:{width:(width-52)/2,minHeight:138},
    visual:{width:92,height:78,borderRadius:24,backgroundColor:c.card3,borderWidth:1,borderColor:c.line,alignItems:'center',justifyContent:'center',overflow:'hidden'},
    visualLarge:{width:'100%',height:150,borderRadius:26},
    glow:{position:'absolute',width:140,height:140,borderRadius:70,backgroundColor:c.goldSoft},
    desk:{position:'absolute',bottom:22,width:126,height:22,borderRadius:10,backgroundColor:c.line,borderWidth:1,borderColor:c.line2},
    board:{width:76,height:54,borderRadius:10,borderWidth:1,borderColor:c.goldLine},
    boardLine:{position:'absolute',height:2,backgroundColor:c.blue,transform:[{rotate:'-20deg'}]},
    dot:{position:'absolute',width:8,height:8,borderRadius:4,backgroundColor:c.gold2},
    report:{width:58,height:66,borderRadius:14,borderWidth:1,borderColor:c.goldLine,backgroundColor:c.line},
    bar:{position:'absolute',left:10,height:6,borderRadius:6,backgroundColor:c.blue},
    financeBar:{position:'absolute',bottom:18,width:11,borderRadius:8,backgroundColor:c.gold2},
    statRow:{flexDirection:'row',marginBottom:14},
    stat:{flex:1,borderRadius:18,borderWidth:1,borderColor:c.line,backgroundColor:c.card3,padding:12,marginRight:8},
    statValue:{color:c.gold2,fontFamily:titleFont,fontSize:20,fontWeight:'900'},
    statLabel:{color:c.soft,fontSize:11,marginTop:4},
    note:{borderWidth:1,borderColor:c.line,borderRadius:18,padding:12,backgroundColor:c.card3,marginTop:12},
    noteLabel:{color:c.gold2,fontWeight:'900',fontSize:12},
    inputLabel:{color:c.gold2,fontWeight:'900',marginTop:10,marginBottom:8},
    input:{backgroundColor:c.card3,borderWidth:1,borderColor:c.line,borderRadius:18,paddingHorizontal:14,paddingVertical:14,color:c.ink,fontSize:15},
    textArea:{minHeight:100,textAlignVertical:'top'},
    langGrid:{flexDirection:'row',flexWrap:'wrap',marginTop:10},
    langChip:{borderWidth:1,borderColor:c.line2,borderRadius:999,paddingHorizontal:12,paddingVertical:9,marginRight:8,marginBottom:8,backgroundColor:c.card3},
    langActive:{backgroundColor:c.gold,borderColor:c.gold},
    langText:{color:c.ink,fontWeight:'900'},
    langTextActive:{color:'#111'},
    themeCard:{flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:c.line,borderRadius:20,padding:12,marginBottom:10,backgroundColor:c.card3},
    themePreview:{width:52,height:42,borderRadius:14,borderWidth:1,borderColor:c.line2,overflow:'hidden',marginRight:12},
    modalRoot:{flex:1,justifyContent:'flex-end'},
    shade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,0.62)'},
    sheet:{maxHeight:'88%',backgroundColor:c.card3,borderTopLeftRadius:34,borderTopRightRadius:34,borderWidth:1,borderColor:c.line,paddingHorizontal:20,paddingTop:12,paddingBottom:28},
    handle:{alignSelf:'center',width:52,height:5,borderRadius:4,backgroundColor:c.line2,marginBottom:16},
    center:{flex:1,alignItems:'center',justifyContent:'center',padding:18},
    centerCard:{width:'100%',maxWidth:460,backgroundColor:c.card3,borderWidth:1,borderColor:c.line2,borderRadius:28,padding:18},
    tab:{position:'absolute',left:0,right:0,bottom:0,height:86,borderTopWidth:1,borderTopColor:c.line,backgroundColor:c.bg,flexDirection:'row',paddingTop:8},
    tabItem:{flex:1,alignItems:'center'},
    tabIcon:{fontSize:23},
    tabText:{color:c.soft,fontSize:10,fontWeight:'900',marginTop:3,maxWidth:76},
    tabTextActive:{color:c.gold2},
    toast:{position:'absolute',left:24,right:24,bottom:100,backgroundColor:c.card2,borderWidth:1,borderColor:c.goldLine,borderRadius:18,padding:14,alignItems:'center'},
    toastText:{color:c.ink,fontWeight:'900'}
  });
}
